Update README.md
It seems recent PyYAML6.0 or later is not compatible with the parseyaml.py, and caused "TypeError: load() missing 1 required positional argument: 'Loader'" error.